language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - 'node'
  - '10'
  - '8'
  - '6'
install:
  - npm i
  - npm i -g mocha codecov eslint
script:
  - if [[ $(node -v) == 'v6.16.0' ]]; then npm run build:all; fi;
  - npm run lint
  - snyk auth $SNYK_TOKEN
  - if [[ $(node -v) == 'v6.16.0' ]]; then npm run test:dist; else npm run test; fi;
  - codecov
after_success:
  - snyk monitor
jobs:
  include:
    - stage: release
      node_js: 'node'
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script: npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
stages:
  - name: release
    if: branch = master
