language: node_js
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
    npm i -g codecov
script:
  - istanbul cover _mocha
after_success:
  - bash <(curl -s https://codecov.io/bash)
# safelist
branches:
  only:
  - master
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/ #vX.Y
